### ISSUE TITLE
HPロゴ追加

### ISSUE THREAD

**Issue by HidetoNiwa** [Kansai-SpringRobocon/kansai-harurobo-hp#119]
![image](https://user-images.githubusercontent.com/30413729/190885456-82591a33-8ec8-47c7-8852-7d608d6038c5.png)

赤まる部分の画像をロゴマーク入りの下記リンク画像に差し替えお願いします。

https://drive.google.com/file/d/1vY_9qv-XqVgxSYxIRiumUoVRgOdfSuxg/view?usp=sharing

**Comment by yn4k4nishi** [comment]
差し替えました
