### ISSUE TITLE
ENTRY 書式崩れ

### ISSUE THREAD

**Issue by HidetoNiwa** [Kansai-SpringRobocon/kansai-harurobo-hp#126]
## 概要
下記部分が1行になってしまっているので、事項ごとに改行お願いします。
> 【New!】10/31 エントリーチーム一覧を公開しました！ 10/09 春ロボコン2023 関西大会の応募要項を公開しました！

## 該当ページ
https://xn--tck4d2b0a0029dol2bn0r.com/entry/

**Comment by HansRobo** [comment]
Close with #127
