### ISSUE TITLE
[スポンサー追加]船井電機 様

### ISSUE THREAD

**Issue by HidetoNiwa** [Kansai-SpringRobocon/kansai-harurobo-hp#130]
スポンサーに関する情報を下記に記入してください、よろしくお願いいたします。

## 企業名
船井電機株式会社 様

## リンク
https://www2.funai.co.jp/index.html

## プラン
- [x] Diamond Sponsor
- [ ] Platinum
- [ ] Gold
- [ ] Silver
- [ ] Bronze

## ロゴデータ
https://kansai-harurobo.slack.com/files/U03SLL9F285/F04DJTU043X/____________.png

**Comment by HansRobo** [comment]
#132 で追加済み
