### ISSUE TITLE
[スポンサー追加]Scramble 様

### ISSUE THREAD

**Issue by HidetoNiwa** [Kansai-SpringRobocon/kansai-harurobo-hp#131]
スポンサーに関する情報を下記に記入してください

## 企業名
一般社団法人 次世代ロボットエンジニア支援機構（Scramble）

## リンク
https://scramble-robot.org/

## プラン

- [ ] Platinum
- [x] Gold
- [ ] Silver
- [ ] Bronze

## ロゴデータ
https://github.com/Kansai-SpringRobocon/kansai-harurobo-hp/issues/102

**Comment by HansRobo** [comment]
#132 で追加済み
