### ISSUE TITLE
スポンサーロゴカラー化

### ISSUE THREAD

**Issue by HidetoNiwa** [Kansai-SpringRobocon/kansai-harurobo-hp#48]
スポンサーロゴ、カーソルをもっていかないと白黒なのあまりイメージよくないと思います...

**Comment by HidetoNiwa** [comment]
スポンサーロゴカラー化と同時に、スポンサーロゴの幅の変更も対応してほしいです。

Twitterで告知前に修正したいので少し早めに対応してほしいです。

**Comment by yn4k4nishi** [comment]
スポンサーのロゴの幅っていうのは、途中で改行が入ってるのが気になるって話ですよね

**Comment by HidetoNiwa** [comment]
@yn4k4nishi そうです～元のThemeとかの関係もあるかもですが
