### ISSUE TITLE
Twitter埋め込み修正

### ISSUE THREAD

**Issue by HidetoNiwa** [Kansai-SpringRobocon/kansai-harurobo-hp#93]
関西大会公式Twitter
Tweets by kansai_robocon

とトップページで書かれているが、Tweetタイムラインが見えていない

下記コードの埋め込みお願いします。
<a class="twitter-timeline" href="https://twitter.com/kansai_robocon?ref_src=twsrc%5Etfw">Tweets by kansai_robocon</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by HansRobo** [comment]
mdファイルに埋め込みコードを貼り付けていたのがよくなかったみたいです．
トップページの元になるhtmlファイルに追加することで解決しました
