### ISSUE TITLE
[スポンサー追加]

### ISSUE THREAD

**Issue by komorimikito** [Kansai-SpringRobocon/kansai-harurobo-hp#95]
スポンサーに関する情報を下記に記入してください

## 企業名
マルホ発條工業株式会社
## リンク
https://www.maruho-htj.co.jp/
## プラン

- [x] Platinum
- [ ] Gold
- [ ] Silver
- [ ] Bronze

## ロゴデータ
![マルホ発條工業株式会社　会社ロゴ](https://user-images.githubusercontent.com/89957467/143818314-cf2960b8-c7a2-4c78-b0d7-15192090a37f.jpg)

**Comment by yn4k4nishi** [comment]
da2a65d27e0bb9efac0c7b755680e7f8aea85dd7

対応しました。
